### ISSUE TITLE
Building the tarball

### ISSUE THREAD

**Issue by justinmoon** [puneetsl/lotion#15]
I'm a a little too paranoid to install a random binary off of GitHub :wink:.

Could you add the ability to build the tarball using nativfier?

**Comment by puneetsl** [comment]
Well, good idea but the Nativefier command is pretty straightforward: 

`nativefier "https://www.notion.so"`

I do some post-processing after creating the app, you can take a look at the source of app.asar in the resources folder.  I made this repo for myself because I do lots of distro-hopping and for people who don't want/know how to install nativefier and npm. 

Even I am paranoid about internet binaries, but at a certain point, we have to take a leap of faith with packages from GitHub, especially Electron apps.

**Comment by justinmoon** [comment]
Thanks for response. Didn't realize it was that simple!
