### ISSUE TITLE
using as root causes close error

### ISSUE THREAD

**Issue by bparks3** [puneetsl/lotion#32]
Hi,
I am using the app in root mode to do so I directly call the Lotion file using the command -
./Lotion --no-sandbox 
All is good when the app is running but problems start to come up when the app is closed I close the app normal way by using the close button on the top left  but the process is  still running in command line not just that when I check the running commands using `ps aux | grep otion` 
I see the process is still running even though I stopped it in terminal using Ctrl + z 
To further stop the process I need to force close it using kill -9 PID.
Is there an issue in the closing task or some other way I could modify it to close the process when I quit the app  (I know we are not supposed to run the app as root )

**Comment by puneetsl** [comment]
This app is designed to be used in a "single instance" and "stay-in-tray" due to which instead of quitting it keeps the process running. 
if you are using any modern UI which supports tray, you can click in tray and quit from there. Otherwise, creating a custom script which find the process id and kills it would be your best option.

I'll try to add shortcut "CTRL+Q" to quit this app permanently.
