### ISSUE TITLE
What is the dock in the README?

### ISSUE THREAD

**Issue by fr3fou** [puneetsl/lotion#7]
Is this a MacOS screenshot?

**Comment by puneetsl** [comment]
Yes! this screenshot is taken directly from [Konrad Kolasa](https://dribbble.com/shots/4886987-Notion-Icon-Replacement)'s dribble page.
Since Linux desktops vary a lot I did not want to impose an image of how it looks on my distro and rather concentrate on the beautiful icon itself.
However here is how it looks on my distro 
![](https://github.com/puneetsl/lotion/blob/master/Notion.png?raw=true)

**Comment by fr3fou** [comment]
What's your GTK  + icon theme?

**Comment by puneetsl** [comment]
![neo](https://user-images.githubusercontent.com/6509604/63205779-78b0ba80-c077-11e9-8bb0-a9a2927a9eb5.png)

**Comment by puneetsl** [comment]
Wallpaper
![minimal-mojave-night-yf](https://user-images.githubusercontent.com/6509604/63205784-87976d00-c077-11e9-99db-c4f0842f0080.jpg)

**Comment by fr3fou** [comment]
thanks!
