### ISSUE TITLE
No shortcut created

### ISSUE THREAD

**Issue by Gontran-Macedoine** [puneetsl/lotion#87]
I think the installation process worked normally, when I go in the Lotion folder and execute ./Lotion I can start the app. However, there is no shortcut/icon in the app launcher and I can't set a keyboard shortcut to launch Lotion...
I'm using Pop_OS up to date

**Comment by joshpetit** [comment]
If you want to set a keyboard shortcut to launch Lotion you'll have to put the full path to the executable since it isn't on your path. The alternative would be too link the executable to your bin
```sh
sudo ln -s /usr/local/bin/lotion /full/path/to/executable
```
I'm not sure why it doesn't show up in your app launcher though. 
Can you verify that your
`~/.local/share/applications/Lotion.desktop` looks like this:
```
[Desktop Entry]
Name=Notion
Name[en_US]=Lotion
Comment=Unofficial Notion.so application for Linux
Exec="/home/user/path/to/lotion/Lotion"
Terminal=false
Categories=Office;TextEditor;Utility
Type=Application
Icon=/home/user/path/to/icon.png
StartupWMClass=Notion
```
If not try creatign that and see if it works.

**Comment by Gontran-Macedoine** [comment]
Many thanks, it worked !
The file didn't exist, I created it and the shortcut had been created !
